//! The published PNX conformance vectors, through `re pnx verify`.
//!
//! `tests/vectors/pnx/conformance/` is a verbatim copy of
//! `tacet/conformance/vectors/v1/pnx_00{2,3,4,5}_*.json` from the Crovia
//! repository (croviatrust.com/registry/tacet/spec/vectors/v1/). They are
//! generated by the Python reference `tacet-pnx` from a deterministic
//! scenario and checked there by a Python and a JavaScript runner. This
//! file is the third runner: every expectation the other two check, the
//! Rust verifier must reproduce — verdicts per asset, the overall verdict,
//! the exit code, the seal binding, and the error a fault produces.
//!
//! The vectors are data, not code: copy new ones over, do not edit them.

use std::{
    fs,
    path::Path,
    process::{Command, Output},
};

use serde_json::Value;

fn re(dir: &Path, args: &[String]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_re"))
        .args(args)
        .current_dir(dir)
        .env("NO_COLOR", "1")
        .output()
        .unwrap()
}

fn vector(name: &str) -> Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/vectors/pnx/conformance")
        .join(name);
    serde_json::from_slice(&fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display())))
        .unwrap()
}

fn report(out: &Output) -> Value {
    serde_json::from_slice(&out.stdout).unwrap_or_else(|e| {
        panic!(
            "{e}: no JSON report\n{}\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )
    })
}

/// Write `assets_hex` (label → hex bytes) into `dir` and return the
/// `--asset LABEL=PATH` arguments naming them.
fn asset_args(dir: &Path, assets_hex: &Value) -> Vec<String> {
    let mut args = Vec::new();
    for (label, hex) in assets_hex.as_object().unwrap() {
        let path = dir.join(format!("{label}.asset"));
        fs::write(&path, hex::decode(hex.as_str().unwrap()).unwrap()).unwrap();
        args.push("--asset".into());
        args.push(format!("{label}={}", path.display()));
    }
    args
}

fn verify(dir: &Path, document: &Value, assets_hex: Option<&Value>) -> (i32, Value) {
    let path = dir.join("proof.json");
    fs::write(&path, serde_json::to_vec(document).unwrap()).unwrap();
    let mut args = vec![
        "pnx".to_string(),
        "verify".into(),
        path.display().to_string(),
    ];
    if let Some(a) = assets_hex {
        args.extend(asset_args(dir, a));
    }
    args.push("--json".into());
    let out = re(dir, &args);
    (out.status.code().unwrap_or(-1), report(&out))
}

fn exit_for(ok: bool, verdict: &str) -> i32 {
    match (ok, verdict) {
        (false, _) => 2,
        (true, "absent") => 0,
        (true, _) => 1,
    }
}

fn errors_joined(rep: &Value) -> String {
    let mut all: Vec<&str> = rep["errors"]
        .as_array()
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    if let Some(s) = rep.get("seal_errors").and_then(Value::as_array) {
        all.extend(s.iter().filter_map(Value::as_str));
    }
    all.join(" | ")
}

// ---------------------------------------------------------------------------

#[test]
fn pnx_002_proofs_verdicts_and_exit_codes() {
    let v = vector("pnx_002_proofs.json");
    let tmp = tempfile::tempdir().unwrap();
    for (name, case) in v["proofs"].as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let (code, rep) = verify(&dir, &case["proof"], Some(&case["assets_hex"]));
        let expect = &case["expect"];
        assert_eq!(rep["ok"], expect["ok"], "{name}: ok\n{rep}");
        assert_eq!(
            rep["verdict"], expect["verdict"],
            "{name}: overall verdict\n{rep}"
        );
        assert_eq!(
            rep["assets"], expect["assets"],
            "{name}: per-asset verdicts\n{rep}"
        );
        assert_eq!(rep["sealed"], false, "{name}");
        assert_eq!(
            code,
            exit_for(true, expect["verdict"].as_str().unwrap()),
            "{name}: exit code\n{rep}"
        );
    }
}

#[test]
fn pnx_002_hash_only_verifies_with_a_warning() {
    let v = vector("pnx_002_proofs.json");
    let tmp = tempfile::tempdir().unwrap();
    let expect = &v["hash_only"]["expect"];
    let needle = expect["warning_contains"].as_str().unwrap();
    for (name, case) in v["proofs"].as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let (code, rep) = verify(&dir, &case["proof"], None);
        assert_eq!(rep["ok"], expect["ok"], "{name}: hash-only ok\n{rep}");
        let warnings = rep["warnings"].to_string();
        assert!(
            warnings.contains(needle),
            "{name}: warning must contain {needle:?}\n{warnings}"
        );
        // The stated verdicts are carried, not recomputed, and the exit code follows them.
        assert_eq!(rep["verdict"], case["expect"]["verdict"], "{name}\n{rep}");
        assert_eq!(
            code,
            exit_for(true, case["expect"]["verdict"].as_str().unwrap()),
            "{name}"
        );
    }
}

#[test]
fn pnx_003_every_fault_is_rejected_with_the_named_error() {
    let v = vector("pnx_003_invalid.json");
    let tmp = tempfile::tempdir().unwrap();
    let mut seen = 0;
    for (name, case) in v.as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let (code, rep) = verify(&dir, &case["proof"], Some(&case["assets_hex"]));
        assert_eq!(rep["ok"], false, "{name}: must be invalid\n{rep}");
        assert_eq!(code, 2, "{name}: exit 2\n{rep}");
        let needle = case["expect_error_contains"].as_str().unwrap();
        let errors = errors_joined(&rep);
        assert!(
            errors.contains(needle),
            "{name}: error must contain {needle:?}\n  got: {errors}"
        );
        seen += 1;
    }
    assert!(
        seen >= 13,
        "the vector file names at least 13 faults, saw {seen}"
    );
}

#[test]
fn pnx_003_hash_only_agrees_on_what_bytes_are_needed_for() {
    // Without asset bytes, a verifier can only check what the proof states
    // about itself. `hash_only_ok` says whether the fault is still visible then.
    let v = vector("pnx_003_invalid.json");
    let tmp = tempfile::tempdir().unwrap();
    for (name, case) in v.as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let (_, rep) = verify(&dir, &case["proof"], None);
        assert_eq!(
            rep["ok"], case["hash_only_ok"],
            "{name}: hash-only ok must match the vector\n{rep}"
        );
    }
}

/// `re pnx verify` with `--policy FILE` (and `--name HOST`), reporting JSON.
fn verify_with_policy(
    dir: &Path,
    document: &Value,
    assets_hex: &Value,
    policy: Option<&Value>,
    names: &[&str],
) -> (i32, Value) {
    let path = dir.join("proof.json");
    fs::write(&path, serde_json::to_vec(document).unwrap()).unwrap();
    let mut args = vec![
        "pnx".to_string(),
        "verify".into(),
        path.display().to_string(),
    ];
    args.extend(asset_args(dir, assets_hex));
    if let Some(p) = policy {
        let ppath = dir.join("policy.json");
        fs::write(&ppath, serde_json::to_vec(p).unwrap()).unwrap();
        args.push("--policy".into());
        args.push(ppath.display().to_string());
    }
    for n in names {
        args.push("--name".into());
        args.push((*n).to_string());
    }
    args.push("--json".into());
    let out = re(dir, &args);
    (out.status.code().unwrap_or(-1), report(&out))
}

#[test]
fn pnx_005_reach_records_verify_with_and_without_the_policy() {
    // The reach sheets of pnx_005 are signed over the run of pnx_002 (same
    // root, same salt), so the `clean` proof of pnx_002 with one of these
    // sheets in place is a complete proof carrying a reach record.
    let v = vector("pnx_005_reach.json");
    let base = vector("pnx_002_proofs.json");
    let clean = &base["proofs"]["clean"];
    let tmp = tempfile::tempdir().unwrap();
    for (name, case) in v["valid"].as_object().unwrap() {
        let sheet = &case["sheet"];
        assert_eq!(
            sheet["root"], base["sheet"]["root"],
            "{name}: same run as pnx_002"
        );
        assert_eq!(sheet["salt_hex"], base["sheet"]["salt_hex"], "{name}");
        let mut proof = clean["proof"].clone();
        proof["sheet"] = sheet.clone();
        let names: Vec<&str> = case["names"]
            .as_array()
            .map(|a| a.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        for (label, policy) in [
            ("expect_with_policy", Some(&v["policy"]["document"])),
            ("expect_without_policy", None),
        ] {
            let dir = tmp.path().join(format!("{name}-{label}"));
            fs::create_dir_all(&dir).unwrap();
            let (code, rep) =
                verify_with_policy(&dir, &proof, &clean["assets_hex"], policy, &names);
            let exp = &case[label];
            assert_eq!(rep["ok"], true, "{name} {label}\n{rep}");
            assert_eq!(rep["verdict"], "absent", "{name} {label}\n{rep}");
            assert_eq!(
                rep["reach"]["verdict"], exp["verdict"],
                "{name} {label}\n{rep}"
            );
            assert_eq!(
                rep["reach"]["outside"], exp["outside"],
                "{name} {label}\n{rep}"
            );
            assert_eq!(
                rep["reach"]["reached"], exp["reached"],
                "{name} {label}\n{rep}"
            );
            if let Some(w) = exp["warning_contains"].as_str() {
                assert!(
                    rep["warnings"].to_string().contains(w),
                    "{name} {label}: warnings must mention {w:?}\n{rep}"
                );
            }
            // outside-policy is a valid proof with exit 1, like `present`.
            let expected = if exp["verdict"] == "outside-policy" {
                1
            } else {
                0
            };
            assert_eq!(code, expected, "{name} {label}: exit code\n{rep}");
        }
    }
}

#[test]
fn pnx_005_every_reach_fault_is_rejected_with_the_named_error() {
    let v = vector("pnx_005_reach.json");
    let base = vector("pnx_002_proofs.json");
    let clean = &base["proofs"]["clean"];
    let tmp = tempfile::tempdir().unwrap();
    let mut seen = 0;
    for (name, case) in v["invalid"].as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let mut proof = clean["proof"].clone();
        proof["sheet"] = case["sheet"].clone();
        let policy = (case["with_policy"] == true).then_some(&v["policy"]["document"]);
        let (code, rep) = verify_with_policy(&dir, &proof, &clean["assets_hex"], policy, &[]);
        assert_eq!(rep["ok"], false, "{name}: must be invalid\n{rep}");
        assert_eq!(code, 2, "{name}: exit 2\n{rep}");
        let needle = case["expect_error_contains"].as_str().unwrap();
        let errors = errors_joined(&rep);
        assert!(
            errors.contains(needle),
            "{name}: error must contain {needle:?}\n  got: {errors}"
        );
        seen += 1;
    }
    assert!(
        seen >= 10,
        "the vector names at least 10 faults, saw {seen}"
    );
}

#[test]
fn pnx_004_sealed_bundles_verify_and_bind() {
    let v = vector("pnx_004_sealed.json");
    let tmp = tempfile::tempdir().unwrap();
    for name in ["clean", "exposure"] {
        let case = &v[name];
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let bundle = serde_json::json!({
            "seal": case["seal"], "query": case["query"], "proof": case["proof"]
        });
        let (code, rep) = verify(&dir, &bundle, Some(&case["assets_hex"]));
        let expect = &case["expect"];
        assert_eq!(rep["ok"], expect["ok"], "{name}\n{rep}");
        assert_eq!(rep["sealed"], true, "{name}");
        assert_eq!(rep["seal_ok"], expect["seal_ok"], "{name}: seal_ok\n{rep}");
        assert_eq!(rep["verdict"], expect["verdict"], "{name}\n{rep}");
        assert_eq!(
            rep["seal_id"], case["seal"]["seal_id"],
            "{name}: seal id reported"
        );
        assert_eq!(
            code,
            exit_for(true, expect["verdict"].as_str().unwrap()),
            "{name}"
        );
    }
}

#[test]
fn pnx_004_sealed_faults_fail_closed_and_report_the_seal_separately() {
    let v = vector("pnx_004_sealed.json");
    let tmp = tempfile::tempdir().unwrap();
    for (name, case) in v["invalid"].as_object().unwrap() {
        let dir = tmp.path().join(name);
        fs::create_dir_all(&dir).unwrap();
        let bundle = serde_json::json!({
            "seal": case["seal"], "query": case["query"], "proof": case["proof"]
        });
        let (code, rep) = verify(&dir, &bundle, Some(&case["assets_hex"]));
        assert_eq!(rep["ok"], false, "{name}: must be invalid\n{rep}");
        assert_eq!(code, 2, "{name}: exit 2");
        // A valid seal over a forged proof is still a valid seal: the two
        // verdicts are separate, and the vector says which one fails.
        assert_eq!(
            rep["seal_signature_ok"], case["expect"]["seal_signature_ok"],
            "{name}: seal signature verdict\n{rep}"
        );
        assert_eq!(rep["ok"], case["expect"]["ok"], "{name}");
        // Whatever the signature says, the seal as a whole never passes here:
        // either it does not verify, or it does not bind what it claims to.
        if name != "forged_verdict_under_valid_seal" {
            assert_eq!(rep["seal_ok"], false, "{name}: seal_ok\n{rep}");
        } else {
            assert_eq!(
                rep["seal_ok"], true,
                "{name}: the seal itself is fine\n{rep}"
            );
        }
        let needle = case["expect_error_contains"].as_str().unwrap();
        let errors = errors_joined(&rep);
        assert!(
            errors.contains(needle),
            "{name}: error must contain {needle:?}\n  got: {errors}"
        );
    }
}
